{
    'name': 'CarrierDashboard',
    'author': "Govind Bhujbal",
    'website': 'www.iqInnovationHub.com',
    'summary': 'Odoo 16 Development app',
    'license': 'AGPL-3',
    'depends': ['purchase','account','product','sale','stock'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/menu.xml',
        'views/CarrierDashboard.xml',
        'views/purchaseorder.xml',
        'views/invoice.xml',
        'views/salescarrier.xml',
        'views/stock_picking.xml',
        'views/house_bill_of_lading.xml',
        'report/report.xml',
        'report/stock_report_picking.xml',
        'report/house_bill_of_lading_template.xml',
        'report/sales_house_bill_of_lading_template.xml',
    ],
    'demo':[],
    'qweb':[],
    'installable':True,
    'application':True,
    'auto_install':False,
}
